modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/Mrbysco/TelePass/issues"
license="MIT"

[[mods]]
modId="telepass"
version="${file.jarVersion}"
displayName="Telepass"
displayURL="https://www.curseforge.com/minecraft/mc-mods/telepass"
authors="Mrbysco"
credits="'Perfect Strange' for the idea"
description='''
Allowing players to teleport to each other
'''
[[dependencies.telepass]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.20.4,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.telepass]]
modId="neoforge"
type="REQUIRED"
versionRange="[20.4.131-beta,)"
ordering="NONE"
side="BOTH"