modLoader="javafml"
loaderVersion="[38,)"
issueTrackerURL="https://github.com/Mrbysco/TelePass/issues"
license="MIT"

[[mods]]
modId="telepass"
version="${file.jarVersion}"
displayName="Telepass"
displayURL="https://www.curseforge.com/minecraft/mc-mods/telepass"
authors="Mrbysco"
credits="'Perfect Strange' for the idea"
description='''
Allowing players to teleport to each other
'''
[[dependencies.telepass]]
modId="minecraft"
mandatory=true
versionRange="[1.18,1.19)"
ordering="NONE"
side="BOTH"